project:
  title: Corpus poético de Fernando de Herrera
  description:
  avatar: avatar.png
  xslt:
  collectors:
    - fullname: Laura Hernández-Lorenzo
      url: https://orcid.org/0000-0003-3489-2193
proposals:
  min_hitrate: 50
subprojects:
  - inpath: /home/jovyan/corpora/herrera
    name: jovyan_corpora_herrera
    outpath: /home/jovyan/workdir/projects/herrera_20251028/jovyan_corpora_herrera/result
    basepath: /home/jovyan/workdir/projects/herrera_20251028/jovyan_corpora_herrera
    files:
      - /home/jovyan/corpora/herrera/B.xml
      - /home/jovyan/corpora/herrera/H.xml
      - /home/jovyan/corpora/herrera/P.xml
      - /home/jovyan/corpora/herrera/P2.xml
      - /home/jovyan/corpora/herrera/Poemas sueltos.xml